- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: copy bash_aliases
      copy:
        src: bash_aliases
        dest: ~/.bash_aliases

    - name: copy gitconfig
      copy:
        src: gitconfig
        dest: ~/.gitconfig

    - name: copy vimrc
      copy:
        src: vimrc
        dest: ~/.vimrc
